name: Server Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Install pnpm
        run: npm install --global corepack@latest && corepack enable pnpm

      - name: Install dependencies
        run: pnpm --shamefully-hoist
      
      - name: Setup environment variables
        run: |
          echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Run development migrations
        run: pnpm db:migrate:dev
      
      - name: Run tests
        run: pnpm test
